apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: scopeplus
  name: scopeplus-svc
spec:
  ports:
  - name: "9080"
    port: 9080
    targetPort: 9080
    nodePort: 30901
  selector:
    name: scopeplus
  type: NodePort
