pipeline {
    tools { 
        maven 'maven' 
        jdk 'JDK' 
    }
    agent {
        node {
            label 'docker-io-ui'
        }
    }
      environment {
        jenkins_openshift_username="c8fdb02e-71cf-4907-963d-19203ee74bb0"
        jenkins_openshift_password="68ec65fb-b20e-4f37-bf26-191bb85d6757"
        ssh_key="github_ssh"
      }

    options { skipDefaultCheckout() }

    stages {
        stage ('Initialize Application Migration') {
            agent none
            steps {
                script {
                        withCredentials(
                                        [string(credentialsId: jenkins_openshift_username, variable: 'OPENSHIFT_ID'),
                                        string(credentialsId: jenkins_openshift_password, variable: 'OPENSHIFT_PASS'),
                                        file(credentialsId: ssh_key, variable: 'PRIVATE_KEY')])
                           {
                        
                                stage ('Ansible Play') {
                                        retry(3) {
                                                sh 'oc login https://openshiftnextgen.in.dst.ibm.com:8443 -u $OPENSHIFT_ID -p $OPENSHIFT_PASS --insecure-skip-tls-verify=true'
                                        }
                                        try {
                                                sh 'oc delete project creditprocessordb-build'
                                        } catch (Exception e) {
                                                echo 'project does not exist'
                                        }
                                        try {
                                                sh 'oc delete project creditprocessordb-dev'
                                        } catch (Exception e) {
                                                echo 'project does not exist'
                                        }
                                        try {
                                                sh 'oc delete project creditprocessordb-stage'
                                        } catch (Exception e) {
                                                echo 'project does not exist'
                                        }
                                        try {
                                                sh 'oc delete project creditprocessordb-prod'
                                        } catch (Exception e) {
                                                echo 'project does not exist'
                                        }
                                        try{
                                                sh 'cp \$PRIVATE_KEY ${PWD}/id_rsa'
                                        }
                                        catch (Exception e) {
                                                echo 'id_rsa file is already present'
                                        }
                                        
                                        sh 'sleep 60'
                                        sh 'rm -rf ansible_playbook_templates_java'
                                        echo 'Cloning repository'
                                        sh 'git clone https://ntooling:3bf14bb1d09b4fa7fe9a49ee601238bd72c23cab@github.ibm.com/ngt/ansible_playbook_templates_java.git'
                                        echo 'Install ansible galaxy'
                                        sh 'ansible-galaxy install -r ansible_playbook_templates_java/requirements.yml --roles-path=ansible_playbook_templates_java/galaxy'
                                        echo 'Applying Ansible playbooks for docker build and push'
                                        sh 'ansible-playbook -i ansible_playbook_templates_java/creditprocessordb/.applier/ ansible_playbook_templates_java/galaxy/openshift-applier/playbooks/openshift-cluster-seed.yml'
                                        sh 'oc project creditprocessordb-build'
                                        sh 'oc create secret generic ssh-secret --from-file=ssh-privatekey=id_rsa --type=kubernetes.io/ssh-auth'
                                }
                         

                        }
                }
            }
        }
    }
}